/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gcap (void)
{
  GtkWidget *gcap;
  GtkWidget *fixed15;
  GtkWidget *image56;
  GtkWidget *button_ajtcap;
  GtkWidget *alignment43;
  GtkWidget *hbox43;
  GtkWidget *image58;
  GtkWidget *label100;
  GtkWidget *button_mdfcap;
  GtkWidget *alignment44;
  GtkWidget *hbox44;
  GtkWidget *image59;
  GtkWidget *label101;
  GtkWidget *button_suppcap;
  GtkWidget *alignment45;
  GtkWidget *hbox45;
  GtkWidget *image60;
  GtkWidget *label102;
  GtkWidget *button_retgcap;
  GtkWidget *alignment46;
  GtkWidget *hbox46;
  GtkWidget *image61;
  GtkWidget *label103;
  GtkWidget *button_rechcap;
  GtkWidget *alignment47;
  GtkWidget *hbox47;
  GtkWidget *image62;
  GtkWidget *label104;
  GtkWidget *button_affcap;
  GtkWidget *alignment42;
  GtkWidget *hbox42;
  GtkWidget *image57;
  GtkWidget *label99;
  GtkWidget *button_msfctcap;
  GtkWidget *alignment81;
  GtkWidget *hbox81;
  GtkWidget *image108;
  GtkWidget *label199;
  GtkWidget *scrolledwindowlcap;
  GtkWidget *viewport1;
  GtkWidget *fixed28;
  GtkWidget *treeview_lcap;
  GtkWidget *button_qcap;
  GtkWidget *alignment87;
  GtkWidget *hbox87;
  GtkWidget *image114;
  GtkWidget *label210;
  GtkWidget *label_lcap;

  gcap = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (gcap, 620, 430);
  gtk_window_set_title (GTK_WINDOW (gcap), _("Gestion des capteurs "));

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (gcap), fixed15);

  image56 = create_pixmap (gcap, "cp2.png");
  gtk_widget_show (image56);
  gtk_fixed_put (GTK_FIXED (fixed15), image56, 0, 0);
  gtk_widget_set_size_request (image56, 620, 430);

  button_ajtcap = gtk_button_new ();
  gtk_widget_show (button_ajtcap);
  gtk_fixed_put (GTK_FIXED (fixed15), button_ajtcap, 168, 400);
  gtk_widget_set_size_request (button_ajtcap, 105, 29);

  alignment43 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment43);
  gtk_container_add (GTK_CONTAINER (button_ajtcap), alignment43);

  hbox43 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox43);
  gtk_container_add (GTK_CONTAINER (alignment43), hbox43);

  image58 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image58);
  gtk_box_pack_start (GTK_BOX (hbox43), image58, FALSE, FALSE, 0);

  label100 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>ajouter</b></span>"));
  gtk_widget_show (label100);
  gtk_box_pack_start (GTK_BOX (hbox43), label100, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label100), TRUE);

  button_mdfcap = gtk_button_new ();
  gtk_widget_show (button_mdfcap);
  gtk_fixed_put (GTK_FIXED (fixed15), button_mdfcap, 328, 400);
  gtk_widget_set_size_request (button_mdfcap, 105, 29);

  alignment44 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment44);
  gtk_container_add (GTK_CONTAINER (button_mdfcap), alignment44);

  hbox44 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox44);
  gtk_container_add (GTK_CONTAINER (alignment44), hbox44);

  image59 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image59);
  gtk_box_pack_start (GTK_BOX (hbox44), image59, FALSE, FALSE, 0);

  label101 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>modifier</b></span>"));
  gtk_widget_show (label101);
  gtk_box_pack_start (GTK_BOX (hbox44), label101, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label101), TRUE);

  button_suppcap = gtk_button_new ();
  gtk_widget_show (button_suppcap);
  gtk_fixed_put (GTK_FIXED (fixed15), button_suppcap, 488, 400);
  gtk_widget_set_size_request (button_suppcap, 105, 29);

  alignment45 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment45);
  gtk_container_add (GTK_CONTAINER (button_suppcap), alignment45);

  hbox45 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox45);
  gtk_container_add (GTK_CONTAINER (alignment45), hbox45);

  image60 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image60);
  gtk_box_pack_start (GTK_BOX (hbox45), image60, FALSE, FALSE, 0);

  label102 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>supprimer</b></span>"));
  gtk_widget_show (label102);
  gtk_box_pack_start (GTK_BOX (hbox45), label102, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label102), TRUE);

  button_retgcap = gtk_button_new ();
  gtk_widget_show (button_retgcap);
  gtk_fixed_put (GTK_FIXED (fixed15), button_retgcap, 445, 0);
  gtk_widget_set_size_request (button_retgcap, 85, 29);

  alignment46 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment46);
  gtk_container_add (GTK_CONTAINER (button_retgcap), alignment46);

  hbox46 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox46);
  gtk_container_add (GTK_CONTAINER (alignment46), hbox46);

  image61 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image61);
  gtk_box_pack_start (GTK_BOX (hbox46), image61, FALSE, FALSE, 0);

  label103 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>retour</b></span>"));
  gtk_widget_show (label103);
  gtk_box_pack_start (GTK_BOX (hbox46), label103, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label103), TRUE);

  button_rechcap = gtk_button_new ();
  gtk_widget_show (button_rechcap);
  gtk_fixed_put (GTK_FIXED (fixed15), button_rechcap, 440, 50);
  gtk_widget_set_size_request (button_rechcap, 105, 29);

  alignment47 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment47);
  gtk_container_add (GTK_CONTAINER (button_rechcap), alignment47);

  hbox47 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox47);
  gtk_container_add (GTK_CONTAINER (alignment47), hbox47);

  image62 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image62);
  gtk_box_pack_start (GTK_BOX (hbox47), image62, FALSE, FALSE, 0);

  label104 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>rechercher</b></span>"));
  gtk_widget_show (label104);
  gtk_box_pack_start (GTK_BOX (hbox47), label104, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label104), TRUE);

  button_affcap = gtk_button_new ();
  gtk_widget_show (button_affcap);
  gtk_fixed_put (GTK_FIXED (fixed15), button_affcap, 8, 400);
  gtk_widget_set_size_request (button_affcap, 105, 29);

  alignment42 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment42);
  gtk_container_add (GTK_CONTAINER (button_affcap), alignment42);

  hbox42 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox42);
  gtk_container_add (GTK_CONTAINER (alignment42), hbox42);

  image57 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image57);
  gtk_box_pack_start (GTK_BOX (hbox42), image57, FALSE, FALSE, 0);

  label99 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>afficher</b></span>"));
  gtk_widget_show (label99);
  gtk_box_pack_start (GTK_BOX (hbox42), label99, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label99), TRUE);

  button_msfctcap = gtk_button_new ();
  gtk_widget_show (button_msfctcap);
  gtk_fixed_put (GTK_FIXED (fixed15), button_msfctcap, 440, 88);
  gtk_widget_set_size_request (button_msfctcap, 105, 29);

  alignment81 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment81);
  gtk_container_add (GTK_CONTAINER (button_msfctcap), alignment81);

  hbox81 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox81);
  gtk_container_add (GTK_CONTAINER (alignment81), hbox81);

  image108 = gtk_image_new_from_stock ("gtk-properties", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image108);
  gtk_box_pack_start (GTK_BOX (hbox81), image108, FALSE, FALSE, 0);

  label199 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>fctcapteur</b></span>\n"));
  gtk_widget_show (label199);
  gtk_box_pack_start (GTK_BOX (hbox81), label199, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label199), TRUE);

  scrolledwindowlcap = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindowlcap);
  gtk_fixed_put (GTK_FIXED (fixed15), scrolledwindowlcap, 0, 152);
  gtk_widget_set_size_request (scrolledwindowlcap, 620, 220);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindowlcap), viewport1);

  fixed28 = gtk_fixed_new ();
  gtk_widget_show (fixed28);
  gtk_container_add (GTK_CONTAINER (viewport1), fixed28);

  treeview_lcap = gtk_tree_view_new ();
  gtk_widget_show (treeview_lcap);
  gtk_fixed_put (GTK_FIXED (fixed28), treeview_lcap, 0, 0);
  gtk_widget_set_size_request (treeview_lcap, 800, 600);

  button_qcap = gtk_button_new ();
  gtk_widget_show (button_qcap);
  gtk_fixed_put (GTK_FIXED (fixed15), button_qcap, 535, 0);
  gtk_widget_set_size_request (button_qcap, 85, 29);

  alignment87 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment87);
  gtk_container_add (GTK_CONTAINER (button_qcap), alignment87);

  hbox87 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox87);
  gtk_container_add (GTK_CONTAINER (alignment87), hbox87);

  image114 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image114);
  gtk_box_pack_start (GTK_BOX (hbox87), image114, FALSE, FALSE, 0);

  label210 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>quitter</b></span>"));
  gtk_widget_show (label210);
  gtk_box_pack_start (GTK_BOX (hbox87), label210, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label210), TRUE);

  label_lcap = gtk_label_new (_("<span foreground=\"black\" ><b>Liste des Capteurs :</b></span>"));
  gtk_widget_show (label_lcap);
  gtk_fixed_put (GTK_FIXED (fixed15), label_lcap, 16, 104);
  gtk_widget_set_size_request (label_lcap, 225, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_lcap), TRUE);

  g_signal_connect ((gpointer) button_ajtcap, "clicked",
                    G_CALLBACK (on_button_ajtcap_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_mdfcap, "clicked",
                    G_CALLBACK (on_button_mdfcap_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_suppcap, "clicked",
                    G_CALLBACK (on_button_suppcap_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retgcap, "clicked",
                    G_CALLBACK (on_button_retgcap_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_rechcap, "clicked",
                    G_CALLBACK (on_button_rechcap_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_affcap, "clicked",
                    G_CALLBACK (on_button_affcap_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_msfctcap, "clicked",
                    G_CALLBACK (on_button_msfctcap_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_lcap, "row_activated",
                    G_CALLBACK (on_treeview_lcap_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_qcap, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gcap, gcap, "gcap");
  GLADE_HOOKUP_OBJECT (gcap, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (gcap, image56, "image56");
  GLADE_HOOKUP_OBJECT (gcap, button_ajtcap, "button_ajtcap");
  GLADE_HOOKUP_OBJECT (gcap, alignment43, "alignment43");
  GLADE_HOOKUP_OBJECT (gcap, hbox43, "hbox43");
  GLADE_HOOKUP_OBJECT (gcap, image58, "image58");
  GLADE_HOOKUP_OBJECT (gcap, label100, "label100");
  GLADE_HOOKUP_OBJECT (gcap, button_mdfcap, "button_mdfcap");
  GLADE_HOOKUP_OBJECT (gcap, alignment44, "alignment44");
  GLADE_HOOKUP_OBJECT (gcap, hbox44, "hbox44");
  GLADE_HOOKUP_OBJECT (gcap, image59, "image59");
  GLADE_HOOKUP_OBJECT (gcap, label101, "label101");
  GLADE_HOOKUP_OBJECT (gcap, button_suppcap, "button_suppcap");
  GLADE_HOOKUP_OBJECT (gcap, alignment45, "alignment45");
  GLADE_HOOKUP_OBJECT (gcap, hbox45, "hbox45");
  GLADE_HOOKUP_OBJECT (gcap, image60, "image60");
  GLADE_HOOKUP_OBJECT (gcap, label102, "label102");
  GLADE_HOOKUP_OBJECT (gcap, button_retgcap, "button_retgcap");
  GLADE_HOOKUP_OBJECT (gcap, alignment46, "alignment46");
  GLADE_HOOKUP_OBJECT (gcap, hbox46, "hbox46");
  GLADE_HOOKUP_OBJECT (gcap, image61, "image61");
  GLADE_HOOKUP_OBJECT (gcap, label103, "label103");
  GLADE_HOOKUP_OBJECT (gcap, button_rechcap, "button_rechcap");
  GLADE_HOOKUP_OBJECT (gcap, alignment47, "alignment47");
  GLADE_HOOKUP_OBJECT (gcap, hbox47, "hbox47");
  GLADE_HOOKUP_OBJECT (gcap, image62, "image62");
  GLADE_HOOKUP_OBJECT (gcap, label104, "label104");
  GLADE_HOOKUP_OBJECT (gcap, button_affcap, "button_affcap");
  GLADE_HOOKUP_OBJECT (gcap, alignment42, "alignment42");
  GLADE_HOOKUP_OBJECT (gcap, hbox42, "hbox42");
  GLADE_HOOKUP_OBJECT (gcap, image57, "image57");
  GLADE_HOOKUP_OBJECT (gcap, label99, "label99");
  GLADE_HOOKUP_OBJECT (gcap, button_msfctcap, "button_msfctcap");
  GLADE_HOOKUP_OBJECT (gcap, alignment81, "alignment81");
  GLADE_HOOKUP_OBJECT (gcap, hbox81, "hbox81");
  GLADE_HOOKUP_OBJECT (gcap, image108, "image108");
  GLADE_HOOKUP_OBJECT (gcap, label199, "label199");
  GLADE_HOOKUP_OBJECT (gcap, scrolledwindowlcap, "scrolledwindowlcap");
  GLADE_HOOKUP_OBJECT (gcap, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (gcap, fixed28, "fixed28");
  GLADE_HOOKUP_OBJECT (gcap, treeview_lcap, "treeview_lcap");
  GLADE_HOOKUP_OBJECT (gcap, button_qcap, "button_qcap");
  GLADE_HOOKUP_OBJECT (gcap, alignment87, "alignment87");
  GLADE_HOOKUP_OBJECT (gcap, hbox87, "hbox87");
  GLADE_HOOKUP_OBJECT (gcap, image114, "image114");
  GLADE_HOOKUP_OBJECT (gcap, label210, "label210");
  GLADE_HOOKUP_OBJECT (gcap, label_lcap, "label_lcap");

  return gcap;
}

GtkWidget*
create_ajcap (void)
{
  GtkWidget *ajcap;
  GtkWidget *fixed16;
  GtkWidget *entry_msidaj;
  GtkWidget *entry_msmraj;
  GtkObject *spinbutton_msjdiaj_adj;
  GtkWidget *spinbutton_msjdiaj;
  GtkObject *spinbutton_msmdiaj_adj;
  GtkWidget *spinbutton_msmdiaj;
  GtkObject *spinbutton_msadiaj_adj;
  GtkWidget *spinbutton_msadiaj;
  GtkWidget *image63;
  GtkWidget *label_mstpaj;
  GtkWidget *label_msidaj;
  GtkWidget *label_msmraj;
  GtkWidget *label_msdiaj;
  GtkWidget *label_msfctaj;
  GtkWidget *label_msemaj;
  GtkWidget *button_mscnfaj;
  GtkWidget *alignment48;
  GtkWidget *hbox48;
  GtkWidget *image64;
  GtkWidget *label113;
  GtkWidget *button_msanlaj;
  GtkWidget *alignment49;
  GtkWidget *hbox49;
  GtkWidget *image65;
  GtkWidget *label114;
  GtkWidget *radiobutton_mstajt;
  GSList *radiobutton_mstajt_group = NULL;
  GtkWidget *radiobutton_mshaj;
  GtkWidget *checkbutton_msofctaj;
  GtkWidget *checkbutton_msnfctaj;
  GtkWidget *combobox_msempaj;
  GtkWidget *button_qajcap;
  GtkWidget *alignment88;
  GtkWidget *hbox88;
  GtkWidget *image115;
  GtkWidget *label211;
  GtkWidget *label_mssmraj;
  GtkWidget *label_msaltaj;

  ajcap = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ajcap, 620, 430);
  gtk_window_set_title (GTK_WINDOW (ajcap), _("Ajout capteur"));

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (ajcap), fixed16);

  entry_msidaj = gtk_entry_new ();
  gtk_widget_show (entry_msidaj);
  gtk_fixed_put (GTK_FIXED (fixed16), entry_msidaj, 280, 40);
  gtk_widget_set_size_request (entry_msidaj, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_msidaj), 8226);

  entry_msmraj = gtk_entry_new ();
  gtk_widget_show (entry_msmraj);
  gtk_fixed_put (GTK_FIXED (fixed16), entry_msmraj, 280, 80);
  gtk_widget_set_size_request (entry_msmraj, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_msmraj), 8226);

  spinbutton_msjdiaj_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_msjdiaj = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_msjdiaj_adj), 1, 0);
  gtk_widget_show (spinbutton_msjdiaj);
  gtk_fixed_put (GTK_FIXED (fixed16), spinbutton_msjdiaj, 280, 120);
  gtk_widget_set_size_request (spinbutton_msjdiaj, 60, 27);

  spinbutton_msmdiaj_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_msmdiaj = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_msmdiaj_adj), 1, 0);
  gtk_widget_show (spinbutton_msmdiaj);
  gtk_fixed_put (GTK_FIXED (fixed16), spinbutton_msmdiaj, 360, 120);
  gtk_widget_set_size_request (spinbutton_msmdiaj, 60, 27);

  spinbutton_msadiaj_adj = gtk_adjustment_new (2020, 1900, 2100, 1, 10, 10);
  spinbutton_msadiaj = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_msadiaj_adj), 1, 0);
  gtk_widget_show (spinbutton_msadiaj);
  gtk_fixed_put (GTK_FIXED (fixed16), spinbutton_msadiaj, 440, 120);
  gtk_widget_set_size_request (spinbutton_msadiaj, 60, 27);

  image63 = create_pixmap (ajcap, "cp1.png");
  gtk_widget_show (image63);
  gtk_fixed_put (GTK_FIXED (fixed16), image63, 0, 0);
  gtk_widget_set_size_request (image63, 620, 430);

  label_mstpaj = gtk_label_new (_("<span foreground=\"black\" ><b>Type :</b></span>"));
  gtk_widget_show (label_mstpaj);
  gtk_fixed_put (GTK_FIXED (fixed16), label_mstpaj, 160, 8);
  gtk_widget_set_size_request (label_mstpaj, 65, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_mstpaj), TRUE);

  label_msidaj = gtk_label_new (_("<span foreground=\"black\" ><b>Identifiant :</b></span>"));
  gtk_widget_show (label_msidaj);
  gtk_fixed_put (GTK_FIXED (fixed16), label_msidaj, 124, 40);
  gtk_widget_set_size_request (label_msidaj, 97, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_msidaj), TRUE);

  label_msmraj = gtk_label_new (_("<span foreground=\"black\" ><b>Marque :</b></span>\n"));
  gtk_widget_show (label_msmraj);
  gtk_fixed_put (GTK_FIXED (fixed16), label_msmraj, 136, 80);
  gtk_widget_set_size_request (label_msmraj, 96, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_msmraj), TRUE);

  label_msdiaj = gtk_label_new (_("<span foreground=\"black\" ><b>Date d'installation :</b></span>"));
  gtk_widget_show (label_msdiaj);
  gtk_fixed_put (GTK_FIXED (fixed16), label_msdiaj, 75, 120);
  gtk_widget_set_size_request (label_msdiaj, 145, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_msdiaj), TRUE);

  label_msfctaj = gtk_label_new (_("<span foreground=\"black\" ><b>Fonctionnement :</b></span>"));
  gtk_widget_show (label_msfctaj);
  gtk_fixed_put (GTK_FIXED (fixed16), label_msfctaj, 88, 160);
  gtk_widget_set_size_request (label_msfctaj, 128, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_msfctaj), TRUE);

  label_msemaj = gtk_label_new (_("<span foreground=\"black\" ><b>Emplacement :</b></span>"));
  gtk_widget_show (label_msemaj);
  gtk_fixed_put (GTK_FIXED (fixed16), label_msemaj, 96, 192);
  gtk_widget_set_size_request (label_msemaj, 129, 41);
  gtk_label_set_use_markup (GTK_LABEL (label_msemaj), TRUE);

  button_mscnfaj = gtk_button_new ();
  gtk_widget_show (button_mscnfaj);
  gtk_fixed_put (GTK_FIXED (fixed16), button_mscnfaj, 250, 400);
  gtk_widget_set_size_request (button_mscnfaj, 105, 29);

  alignment48 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment48);
  gtk_container_add (GTK_CONTAINER (button_mscnfaj), alignment48);

  hbox48 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox48);
  gtk_container_add (GTK_CONTAINER (alignment48), hbox48);

  image64 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image64);
  gtk_box_pack_start (GTK_BOX (hbox48), image64, FALSE, FALSE, 0);

  label113 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>confirmer</b></span>"));
  gtk_widget_show (label113);
  gtk_box_pack_start (GTK_BOX (hbox48), label113, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label113), TRUE);

  button_msanlaj = gtk_button_new ();
  gtk_widget_show (button_msanlaj);
  gtk_fixed_put (GTK_FIXED (fixed16), button_msanlaj, 400, 400);
  gtk_widget_set_size_request (button_msanlaj, 105, 29);

  alignment49 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment49);
  gtk_container_add (GTK_CONTAINER (button_msanlaj), alignment49);

  hbox49 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox49);
  gtk_container_add (GTK_CONTAINER (alignment49), hbox49);

  image65 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image65);
  gtk_box_pack_start (GTK_BOX (hbox49), image65, FALSE, FALSE, 0);

  label114 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>annuler</b></span>"));
  gtk_widget_show (label114);
  gtk_box_pack_start (GTK_BOX (hbox49), label114, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label114), TRUE);

  radiobutton_mstajt = gtk_radio_button_new_with_mnemonic (NULL, _("temperature"));
  gtk_widget_show (radiobutton_mstajt);
  gtk_fixed_put (GTK_FIXED (fixed16), radiobutton_mstajt, 280, 8);
  gtk_widget_set_size_request (radiobutton_mstajt, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_mstajt), radiobutton_mstajt_group);
  radiobutton_mstajt_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_mstajt));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton_mstajt), TRUE);

  radiobutton_mshaj = gtk_radio_button_new_with_mnemonic (NULL, _("humidite"));
  gtk_widget_show (radiobutton_mshaj);
  gtk_fixed_put (GTK_FIXED (fixed16), radiobutton_mshaj, 416, 8);
  gtk_widget_set_size_request (radiobutton_mshaj, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_mshaj), radiobutton_mstajt_group);
  radiobutton_mstajt_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_mshaj));

  checkbutton_msofctaj = gtk_check_button_new_with_mnemonic (_("oui"));
  gtk_widget_show (checkbutton_msofctaj);
  gtk_fixed_put (GTK_FIXED (fixed16), checkbutton_msofctaj, 280, 168);
  gtk_widget_set_size_request (checkbutton_msofctaj, 72, 24);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton_msofctaj), TRUE);

  checkbutton_msnfctaj = gtk_check_button_new_with_mnemonic (_("non"));
  gtk_widget_show (checkbutton_msnfctaj);
  gtk_fixed_put (GTK_FIXED (fixed16), checkbutton_msnfctaj, 376, 168);
  gtk_widget_set_size_request (checkbutton_msnfctaj, 118, 24);

  combobox_msempaj = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_msempaj);
  gtk_fixed_put (GTK_FIXED (fixed16), combobox_msempaj, 280, 200);
  gtk_widget_set_size_request (combobox_msempaj, 160, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_msempaj), _("Zone-A"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_msempaj), _("Zone-B"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_msempaj), _("Zone-C"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_msempaj), _("Zone-D"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_msempaj), _("Zone-E"));

  button_qajcap = gtk_button_new ();
  gtk_widget_show (button_qajcap);
  gtk_fixed_put (GTK_FIXED (fixed16), button_qajcap, 535, 0);
  gtk_widget_set_size_request (button_qajcap, 85, 29);

  alignment88 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment88);
  gtk_container_add (GTK_CONTAINER (button_qajcap), alignment88);

  hbox88 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox88);
  gtk_container_add (GTK_CONTAINER (alignment88), hbox88);

  image115 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image115);
  gtk_box_pack_start (GTK_BOX (hbox88), image115, FALSE, FALSE, 0);

  label211 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>quitter</b></span>"));
  gtk_widget_show (label211);
  gtk_box_pack_start (GTK_BOX (hbox88), label211, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label211), TRUE);

  label_mssmraj = gtk_label_new (_("<span foreground=\"blue\" ><b>*champ obligatoire</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed16), label_mssmraj, 448, 80);
  gtk_widget_set_size_request (label_mssmraj, 161, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_mssmraj), TRUE);

  label_msaltaj = gtk_label_new (_("<span foreground=\"red\" ><b>Identifiant existe!</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed16), label_msaltaj, 256, 328);
  gtk_widget_set_size_request (label_msaltaj, 161, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_msaltaj), TRUE);

  g_signal_connect ((gpointer) button_mscnfaj, "clicked",
                    G_CALLBACK (on_button_mscnfaj_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_msanlaj, "clicked",
                    G_CALLBACK (on_button_msanlaj_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_mstajt, "toggled",
                    G_CALLBACK (on_radiobutton_mstajt_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_mshaj, "toggled",
                    G_CALLBACK (on_radiobutton_mshaj_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_msofctaj, "toggled",
                    G_CALLBACK (on_checkbutton_msofctaj_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_msnfctaj, "toggled",
                    G_CALLBACK (on_checkbutton_msnfctaj_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_qajcap, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajcap, ajcap, "ajcap");
  GLADE_HOOKUP_OBJECT (ajcap, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (ajcap, entry_msidaj, "entry_msidaj");
  GLADE_HOOKUP_OBJECT (ajcap, entry_msmraj, "entry_msmraj");
  GLADE_HOOKUP_OBJECT (ajcap, spinbutton_msjdiaj, "spinbutton_msjdiaj");
  GLADE_HOOKUP_OBJECT (ajcap, spinbutton_msmdiaj, "spinbutton_msmdiaj");
  GLADE_HOOKUP_OBJECT (ajcap, spinbutton_msadiaj, "spinbutton_msadiaj");
  GLADE_HOOKUP_OBJECT (ajcap, image63, "image63");
  GLADE_HOOKUP_OBJECT (ajcap, label_mstpaj, "label_mstpaj");
  GLADE_HOOKUP_OBJECT (ajcap, label_msidaj, "label_msidaj");
  GLADE_HOOKUP_OBJECT (ajcap, label_msmraj, "label_msmraj");
  GLADE_HOOKUP_OBJECT (ajcap, label_msdiaj, "label_msdiaj");
  GLADE_HOOKUP_OBJECT (ajcap, label_msfctaj, "label_msfctaj");
  GLADE_HOOKUP_OBJECT (ajcap, label_msemaj, "label_msemaj");
  GLADE_HOOKUP_OBJECT (ajcap, button_mscnfaj, "button_mscnfaj");
  GLADE_HOOKUP_OBJECT (ajcap, alignment48, "alignment48");
  GLADE_HOOKUP_OBJECT (ajcap, hbox48, "hbox48");
  GLADE_HOOKUP_OBJECT (ajcap, image64, "image64");
  GLADE_HOOKUP_OBJECT (ajcap, label113, "label113");
  GLADE_HOOKUP_OBJECT (ajcap, button_msanlaj, "button_msanlaj");
  GLADE_HOOKUP_OBJECT (ajcap, alignment49, "alignment49");
  GLADE_HOOKUP_OBJECT (ajcap, hbox49, "hbox49");
  GLADE_HOOKUP_OBJECT (ajcap, image65, "image65");
  GLADE_HOOKUP_OBJECT (ajcap, label114, "label114");
  GLADE_HOOKUP_OBJECT (ajcap, radiobutton_mstajt, "radiobutton_mstajt");
  GLADE_HOOKUP_OBJECT (ajcap, radiobutton_mshaj, "radiobutton_mshaj");
  GLADE_HOOKUP_OBJECT (ajcap, checkbutton_msofctaj, "checkbutton_msofctaj");
  GLADE_HOOKUP_OBJECT (ajcap, checkbutton_msnfctaj, "checkbutton_msnfctaj");
  GLADE_HOOKUP_OBJECT (ajcap, combobox_msempaj, "combobox_msempaj");
  GLADE_HOOKUP_OBJECT (ajcap, button_qajcap, "button_qajcap");
  GLADE_HOOKUP_OBJECT (ajcap, alignment88, "alignment88");
  GLADE_HOOKUP_OBJECT (ajcap, hbox88, "hbox88");
  GLADE_HOOKUP_OBJECT (ajcap, image115, "image115");
  GLADE_HOOKUP_OBJECT (ajcap, label211, "label211");
  GLADE_HOOKUP_OBJECT (ajcap, label_mssmraj, "label_mssmraj");
  GLADE_HOOKUP_OBJECT (ajcap, label_msaltaj, "label_msaltaj");

  return ajcap;
}

GtkWidget*
create_mdfcap (void)
{
  GtkWidget *mdfcap;
  GtkWidget *fixed17;
  GtkWidget *image66;
  GtkWidget *entry_msmrmdf;
  GtkObject *spinbutton_msjdimdf_adj;
  GtkWidget *spinbutton_msjdimdf;
  GtkObject *spinbutton_msmdimdf_adj;
  GtkWidget *spinbutton_msmdimdf;
  GtkObject *spinbutton_msadimdf_adj;
  GtkWidget *spinbutton_msadimdf;
  GtkWidget *button_mscnfmdf;
  GtkWidget *alignment50;
  GtkWidget *hbox50;
  GtkWidget *image67;
  GtkWidget *label123;
  GtkWidget *button_msanlmdf;
  GtkWidget *alignment51;
  GtkWidget *hbox51;
  GtkWidget *image68;
  GtkWidget *label124;
  GtkWidget *label_msidmdf;
  GtkWidget *label_mstpmdf;
  GtkWidget *label_msemmdf;
  GtkWidget *combobox_msempmdf;
  GtkWidget *label_msfctmdf;
  GtkWidget *checkbutton_msofctmdf;
  GtkWidget *checkbutton_msnfctmdf;
  GtkWidget *label_msdimdf;
  GtkWidget *label_msmrmdf;
  GtkWidget *button_mschidmdf;
  GtkWidget *alignment83;
  GtkWidget *hbox83;
  GtkWidget *image110;
  GtkWidget *label204;
  GtkWidget *radiobutton_mshmdf;
  GSList *radiobutton_mshmdf_group = NULL;
  GtkWidget *button_mscnfidmdf;
  GtkWidget *alignment84;
  GtkWidget *hbox84;
  GtkWidget *image111;
  GtkWidget *label206;
  GtkWidget *button_msanlidmdf;
  GtkWidget *alignment85;
  GtkWidget *hbox85;
  GtkWidget *image112;
  GtkWidget *label207;
  GtkWidget *combobox_msidmdf;
  GtkWidget *button_qmdfcap;
  GtkWidget *alignment89;
  GtkWidget *hbox89;
  GtkWidget *image116;
  GtkWidget *label212;
  GtkWidget *label_msanlchmdf;
  GtkWidget *label_mschmdf;
  GtkWidget *radiobutton_mstmdf;

  mdfcap = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (mdfcap, 620, 430);
  gtk_window_set_title (GTK_WINDOW (mdfcap), _("Modifier information capteur"));

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (mdfcap), fixed17);

  image66 = create_pixmap (mdfcap, "cp1.png");
  gtk_widget_show (image66);
  gtk_fixed_put (GTK_FIXED (fixed17), image66, 0, 0);
  gtk_widget_set_size_request (image66, 620, 430);

  entry_msmrmdf = gtk_entry_new ();
  gtk_widget_show (entry_msmrmdf);
  gtk_fixed_put (GTK_FIXED (fixed17), entry_msmrmdf, 272, 152);
  gtk_widget_set_size_request (entry_msmrmdf, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_msmrmdf), 8226);

  spinbutton_msjdimdf_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_msjdimdf = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_msjdimdf_adj), 1, 0);
  gtk_widget_show (spinbutton_msjdimdf);
  gtk_fixed_put (GTK_FIXED (fixed17), spinbutton_msjdimdf, 272, 192);
  gtk_widget_set_size_request (spinbutton_msjdimdf, 60, 27);

  spinbutton_msmdimdf_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_msmdimdf = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_msmdimdf_adj), 1, 0);
  gtk_widget_show (spinbutton_msmdimdf);
  gtk_fixed_put (GTK_FIXED (fixed17), spinbutton_msmdimdf, 352, 192);
  gtk_widget_set_size_request (spinbutton_msmdimdf, 60, 27);

  spinbutton_msadimdf_adj = gtk_adjustment_new (2020, 1900, 2100, 1, 10, 10);
  spinbutton_msadimdf = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_msadimdf_adj), 1, 0);
  gtk_widget_show (spinbutton_msadimdf);
  gtk_fixed_put (GTK_FIXED (fixed17), spinbutton_msadimdf, 432, 192);
  gtk_widget_set_size_request (spinbutton_msadimdf, 60, 27);

  button_mscnfmdf = gtk_button_new ();
  gtk_widget_show (button_mscnfmdf);
  gtk_fixed_put (GTK_FIXED (fixed17), button_mscnfmdf, 250, 400);
  gtk_widget_set_size_request (button_mscnfmdf, 105, 29);

  alignment50 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment50);
  gtk_container_add (GTK_CONTAINER (button_mscnfmdf), alignment50);

  hbox50 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox50);
  gtk_container_add (GTK_CONTAINER (alignment50), hbox50);

  image67 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image67);
  gtk_box_pack_start (GTK_BOX (hbox50), image67, FALSE, FALSE, 0);

  label123 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>confirmer</b></span>\n"));
  gtk_widget_show (label123);
  gtk_box_pack_start (GTK_BOX (hbox50), label123, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label123), TRUE);

  button_msanlmdf = gtk_button_new ();
  gtk_widget_show (button_msanlmdf);
  gtk_fixed_put (GTK_FIXED (fixed17), button_msanlmdf, 400, 400);
  gtk_widget_set_size_request (button_msanlmdf, 105, 29);

  alignment51 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment51);
  gtk_container_add (GTK_CONTAINER (button_msanlmdf), alignment51);

  hbox51 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox51);
  gtk_container_add (GTK_CONTAINER (alignment51), hbox51);

  image68 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image68);
  gtk_box_pack_start (GTK_BOX (hbox51), image68, FALSE, FALSE, 0);

  label124 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>annuler</b></span>"));
  gtk_widget_show (label124);
  gtk_box_pack_start (GTK_BOX (hbox51), label124, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label124), TRUE);

  label_msidmdf = gtk_label_new (_("<span foreground=\"black\" ><b>Identifiant :</b></span>"));
  gtk_widget_show (label_msidmdf);
  gtk_fixed_put (GTK_FIXED (fixed17), label_msidmdf, 144, 48);
  gtk_widget_set_size_request (label_msidmdf, 97, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_msidmdf), TRUE);

  label_mstpmdf = gtk_label_new (_("<span foreground=\"black\" ><b>Type :</b></span>"));
  gtk_widget_show (label_mstpmdf);
  gtk_fixed_put (GTK_FIXED (fixed17), label_mstpmdf, 168, 16);
  gtk_widget_set_size_request (label_mstpmdf, 81, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_mstpmdf), TRUE);

  label_msemmdf = gtk_label_new (_("<span foreground=\"black\" ><b>Emplacement :</b></span>"));
  gtk_widget_show (label_msemmdf);
  gtk_fixed_put (GTK_FIXED (fixed17), label_msemmdf, 112, 264);
  gtk_widget_set_size_request (label_msemmdf, 113, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_msemmdf), TRUE);

  combobox_msempmdf = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_msempmdf);
  gtk_fixed_put (GTK_FIXED (fixed17), combobox_msempmdf, 272, 264);
  gtk_widget_set_size_request (combobox_msempmdf, 160, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_msempmdf), _("Zone-A"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_msempmdf), _("Zone-B"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_msempmdf), _("Zone-C"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_msempmdf), _("Zone-D"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_msempmdf), _("Zone-E"));

  label_msfctmdf = gtk_label_new (_("<span foreground=\"black\" ><b>Fonctionnement :</b></span>"));
  gtk_widget_show (label_msfctmdf);
  gtk_fixed_put (GTK_FIXED (fixed17), label_msfctmdf, 80, 224);
  gtk_widget_set_size_request (label_msfctmdf, 161, 41);
  gtk_label_set_use_markup (GTK_LABEL (label_msfctmdf), TRUE);

  checkbutton_msofctmdf = gtk_check_button_new_with_mnemonic (_("oui"));
  gtk_widget_show (checkbutton_msofctmdf);
  gtk_fixed_put (GTK_FIXED (fixed17), checkbutton_msofctmdf, 272, 224);
  gtk_widget_set_size_request (checkbutton_msofctmdf, 80, 24);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (checkbutton_msofctmdf), TRUE);

  checkbutton_msnfctmdf = gtk_check_button_new_with_mnemonic (_("non"));
  gtk_widget_show (checkbutton_msnfctmdf);
  gtk_fixed_put (GTK_FIXED (fixed17), checkbutton_msnfctmdf, 368, 224);
  gtk_widget_set_size_request (checkbutton_msnfctmdf, 118, 24);

  label_msdimdf = gtk_label_new (_("<span foreground=\"black\" ><b>Date d'installation :</b></span>"));
  gtk_widget_show (label_msdimdf);
  gtk_fixed_put (GTK_FIXED (fixed17), label_msdimdf, 72, 192);
  gtk_widget_set_size_request (label_msdimdf, 152, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_msdimdf), TRUE);

  label_msmrmdf = gtk_label_new (_("<span foreground=\"black\" ><b>Marque :</b></span>\n"));
  gtk_widget_show (label_msmrmdf);
  gtk_fixed_put (GTK_FIXED (fixed17), label_msmrmdf, 136, 160);
  gtk_widget_set_size_request (label_msmrmdf, 104, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_msmrmdf), TRUE);

  button_mschidmdf = gtk_button_new ();
  gtk_widget_show (button_mschidmdf);
  gtk_fixed_put (GTK_FIXED (fixed17), button_mschidmdf, 455, 46);
  gtk_widget_set_size_request (button_mschidmdf, 85, 29);

  alignment83 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment83);
  gtk_container_add (GTK_CONTAINER (button_mschidmdf), alignment83);

  hbox83 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox83);
  gtk_container_add (GTK_CONTAINER (alignment83), hbox83);

  image110 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image110);
  gtk_box_pack_start (GTK_BOX (hbox83), image110, FALSE, FALSE, 0);

  label204 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>charger</b></span>"));
  gtk_widget_show (label204);
  gtk_box_pack_start (GTK_BOX (hbox83), label204, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label204), TRUE);

  radiobutton_mshmdf = gtk_radio_button_new_with_mnemonic (NULL, _("humidite"));
  gtk_widget_show (radiobutton_mshmdf);
  gtk_fixed_put (GTK_FIXED (fixed17), radiobutton_mshmdf, 400, 8);
  gtk_widget_set_size_request (radiobutton_mshmdf, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_mshmdf), radiobutton_mshmdf_group);
  radiobutton_mshmdf_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_mshmdf));

  button_mscnfidmdf = gtk_button_new ();
  gtk_widget_show (button_mscnfidmdf);
  gtk_fixed_put (GTK_FIXED (fixed17), button_mscnfidmdf, 240, 112);
  gtk_widget_set_size_request (button_mscnfidmdf, 85, 29);

  alignment84 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment84);
  gtk_container_add (GTK_CONTAINER (button_mscnfidmdf), alignment84);

  hbox84 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox84);
  gtk_container_add (GTK_CONTAINER (alignment84), hbox84);

  image111 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image111);
  gtk_box_pack_start (GTK_BOX (hbox84), image111, FALSE, FALSE, 0);

  label206 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>valider</b></span>"));
  gtk_widget_show (label206);
  gtk_box_pack_start (GTK_BOX (hbox84), label206, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label206), TRUE);

  button_msanlidmdf = gtk_button_new ();
  gtk_widget_show (button_msanlidmdf);
  gtk_fixed_put (GTK_FIXED (fixed17), button_msanlidmdf, 368, 112);
  gtk_widget_set_size_request (button_msanlidmdf, 85, 29);

  alignment85 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment85);
  gtk_container_add (GTK_CONTAINER (button_msanlidmdf), alignment85);

  hbox85 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox85);
  gtk_container_add (GTK_CONTAINER (alignment85), hbox85);

  image112 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image112);
  gtk_box_pack_start (GTK_BOX (hbox85), image112, FALSE, FALSE, 0);

  label207 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>annuler</b></span>"));
  gtk_widget_show (label207);
  gtk_box_pack_start (GTK_BOX (hbox85), label207, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label207), TRUE);

  combobox_msidmdf = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_msidmdf);
  gtk_fixed_put (GTK_FIXED (fixed17), combobox_msidmdf, 270, 44);
  gtk_widget_set_size_request (combobox_msidmdf, 162, 31);

  button_qmdfcap = gtk_button_new ();
  gtk_widget_show (button_qmdfcap);
  gtk_fixed_put (GTK_FIXED (fixed17), button_qmdfcap, 535, 0);
  gtk_widget_set_size_request (button_qmdfcap, 85, 29);

  alignment89 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment89);
  gtk_container_add (GTK_CONTAINER (button_qmdfcap), alignment89);

  hbox89 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox89);
  gtk_container_add (GTK_CONTAINER (alignment89), hbox89);

  image116 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image116);
  gtk_box_pack_start (GTK_BOX (hbox89), image116, FALSE, FALSE, 0);

  label212 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>quitter</b></span>"));
  gtk_widget_show (label212);
  gtk_box_pack_start (GTK_BOX (hbox89), label212, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label212), TRUE);

  label_msanlchmdf = gtk_label_new (_("<span foreground=\"blue\" ><b>saisir les nouvelles informations </b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed17), label_msanlchmdf, 208, 72);
  gtk_widget_set_size_request (label_msanlchmdf, 249, 41);
  gtk_label_set_use_markup (GTK_LABEL (label_msanlchmdf), TRUE);

  label_mschmdf = gtk_label_new (_("<span foreground=\"blue\" ><b>voulez vous recuperer les informations precedentes</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed17), label_mschmdf, 104, 72);
  gtk_widget_set_size_request (label_mschmdf, 425, 41);
  gtk_label_set_use_markup (GTK_LABEL (label_mschmdf), TRUE);

  radiobutton_mstmdf = gtk_radio_button_new_with_mnemonic (NULL, _("temperature"));
  gtk_widget_show (radiobutton_mstmdf);
  gtk_fixed_put (GTK_FIXED (fixed17), radiobutton_mstmdf, 272, 8);
  gtk_widget_set_size_request (radiobutton_mstmdf, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_mstmdf), radiobutton_mshmdf_group);
  radiobutton_mshmdf_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_mstmdf));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobutton_mstmdf), TRUE);

  g_signal_connect ((gpointer) button_mscnfmdf, "clicked",
                    G_CALLBACK (on_button_mscnfmdf_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_msanlmdf, "clicked",
                    G_CALLBACK (on_button_msanlmdf_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_msofctmdf, "toggled",
                    G_CALLBACK (on_checkbutton_msofctmdf_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_msnfctmdf, "toggled",
                    G_CALLBACK (on_checkbutton_msnfctmdf_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_mschidmdf, "clicked",
                    G_CALLBACK (on_button_mschidmdf_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_mshmdf, "toggled",
                    G_CALLBACK (on_radiobutton_mshmdf_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_mscnfidmdf, "clicked",
                    G_CALLBACK (on_button_mscnfidmdf_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_msanlidmdf, "clicked",
                    G_CALLBACK (on_button_msanlidmdf_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_qmdfcap, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_mstmdf, "toggled",
                    G_CALLBACK (on_radiobutton_mstmdf_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mdfcap, mdfcap, "mdfcap");
  GLADE_HOOKUP_OBJECT (mdfcap, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (mdfcap, image66, "image66");
  GLADE_HOOKUP_OBJECT (mdfcap, entry_msmrmdf, "entry_msmrmdf");
  GLADE_HOOKUP_OBJECT (mdfcap, spinbutton_msjdimdf, "spinbutton_msjdimdf");
  GLADE_HOOKUP_OBJECT (mdfcap, spinbutton_msmdimdf, "spinbutton_msmdimdf");
  GLADE_HOOKUP_OBJECT (mdfcap, spinbutton_msadimdf, "spinbutton_msadimdf");
  GLADE_HOOKUP_OBJECT (mdfcap, button_mscnfmdf, "button_mscnfmdf");
  GLADE_HOOKUP_OBJECT (mdfcap, alignment50, "alignment50");
  GLADE_HOOKUP_OBJECT (mdfcap, hbox50, "hbox50");
  GLADE_HOOKUP_OBJECT (mdfcap, image67, "image67");
  GLADE_HOOKUP_OBJECT (mdfcap, label123, "label123");
  GLADE_HOOKUP_OBJECT (mdfcap, button_msanlmdf, "button_msanlmdf");
  GLADE_HOOKUP_OBJECT (mdfcap, alignment51, "alignment51");
  GLADE_HOOKUP_OBJECT (mdfcap, hbox51, "hbox51");
  GLADE_HOOKUP_OBJECT (mdfcap, image68, "image68");
  GLADE_HOOKUP_OBJECT (mdfcap, label124, "label124");
  GLADE_HOOKUP_OBJECT (mdfcap, label_msidmdf, "label_msidmdf");
  GLADE_HOOKUP_OBJECT (mdfcap, label_mstpmdf, "label_mstpmdf");
  GLADE_HOOKUP_OBJECT (mdfcap, label_msemmdf, "label_msemmdf");
  GLADE_HOOKUP_OBJECT (mdfcap, combobox_msempmdf, "combobox_msempmdf");
  GLADE_HOOKUP_OBJECT (mdfcap, label_msfctmdf, "label_msfctmdf");
  GLADE_HOOKUP_OBJECT (mdfcap, checkbutton_msofctmdf, "checkbutton_msofctmdf");
  GLADE_HOOKUP_OBJECT (mdfcap, checkbutton_msnfctmdf, "checkbutton_msnfctmdf");
  GLADE_HOOKUP_OBJECT (mdfcap, label_msdimdf, "label_msdimdf");
  GLADE_HOOKUP_OBJECT (mdfcap, label_msmrmdf, "label_msmrmdf");
  GLADE_HOOKUP_OBJECT (mdfcap, button_mschidmdf, "button_mschidmdf");
  GLADE_HOOKUP_OBJECT (mdfcap, alignment83, "alignment83");
  GLADE_HOOKUP_OBJECT (mdfcap, hbox83, "hbox83");
  GLADE_HOOKUP_OBJECT (mdfcap, image110, "image110");
  GLADE_HOOKUP_OBJECT (mdfcap, label204, "label204");
  GLADE_HOOKUP_OBJECT (mdfcap, radiobutton_mshmdf, "radiobutton_mshmdf");
  GLADE_HOOKUP_OBJECT (mdfcap, button_mscnfidmdf, "button_mscnfidmdf");
  GLADE_HOOKUP_OBJECT (mdfcap, alignment84, "alignment84");
  GLADE_HOOKUP_OBJECT (mdfcap, hbox84, "hbox84");
  GLADE_HOOKUP_OBJECT (mdfcap, image111, "image111");
  GLADE_HOOKUP_OBJECT (mdfcap, label206, "label206");
  GLADE_HOOKUP_OBJECT (mdfcap, button_msanlidmdf, "button_msanlidmdf");
  GLADE_HOOKUP_OBJECT (mdfcap, alignment85, "alignment85");
  GLADE_HOOKUP_OBJECT (mdfcap, hbox85, "hbox85");
  GLADE_HOOKUP_OBJECT (mdfcap, image112, "image112");
  GLADE_HOOKUP_OBJECT (mdfcap, label207, "label207");
  GLADE_HOOKUP_OBJECT (mdfcap, combobox_msidmdf, "combobox_msidmdf");
  GLADE_HOOKUP_OBJECT (mdfcap, button_qmdfcap, "button_qmdfcap");
  GLADE_HOOKUP_OBJECT (mdfcap, alignment89, "alignment89");
  GLADE_HOOKUP_OBJECT (mdfcap, hbox89, "hbox89");
  GLADE_HOOKUP_OBJECT (mdfcap, image116, "image116");
  GLADE_HOOKUP_OBJECT (mdfcap, label212, "label212");
  GLADE_HOOKUP_OBJECT (mdfcap, label_msanlchmdf, "label_msanlchmdf");
  GLADE_HOOKUP_OBJECT (mdfcap, label_mschmdf, "label_mschmdf");
  GLADE_HOOKUP_OBJECT (mdfcap, radiobutton_mstmdf, "radiobutton_mstmdf");

  return mdfcap;
}

GtkWidget*
create_rechcap (void)
{
  GtkWidget *rechcap;
  GtkWidget *fixed18;
  GtkWidget *image69;
  GtkWidget *button_msretrech;
  GtkWidget *alignment52;
  GtkWidget *hbox52;
  GtkWidget *image70;
  GtkWidget *label126;
  GtkWidget *entry_msidrech;
  GtkWidget *scrolledwindow_rechcap;
  GtkWidget *viewport2;
  GtkWidget *fixed29;
  GtkWidget *treeview_mstxtrech;
  GtkWidget *button_mscnfrech;
  GtkWidget *alignment74;
  GtkWidget *hbox74;
  GtkWidget *image100;
  GtkWidget *label186;
  GtkWidget *label_msidrech;
  GtkWidget *label214;
  GtkWidget *combobox_mscrrech;
  GtkWidget *button_qrechcap;
  GtkWidget *alignment90;
  GtkWidget *hbox90;
  GtkWidget *image117;
  GtkWidget *label213;
  GtkWidget *label_mstxtrech;
  GtkWidget *label_msidaltrech;

  rechcap = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (rechcap, 620, 430);
  gtk_window_set_title (GTK_WINDOW (rechcap), _("Recherche capteur"));

  fixed18 = gtk_fixed_new ();
  gtk_widget_show (fixed18);
  gtk_container_add (GTK_CONTAINER (rechcap), fixed18);

  image69 = create_pixmap (rechcap, "cp1.png");
  gtk_widget_show (image69);
  gtk_fixed_put (GTK_FIXED (fixed18), image69, 0, 0);
  gtk_widget_set_size_request (image69, 620, 430);

  button_msretrech = gtk_button_new ();
  gtk_widget_show (button_msretrech);
  gtk_fixed_put (GTK_FIXED (fixed18), button_msretrech, 445, 0);
  gtk_widget_set_size_request (button_msretrech, 85, 29);

  alignment52 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment52);
  gtk_container_add (GTK_CONTAINER (button_msretrech), alignment52);

  hbox52 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox52);
  gtk_container_add (GTK_CONTAINER (alignment52), hbox52);

  image70 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image70);
  gtk_box_pack_start (GTK_BOX (hbox52), image70, FALSE, FALSE, 0);

  label126 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>retour</b></span>"));
  gtk_widget_show (label126);
  gtk_box_pack_start (GTK_BOX (hbox52), label126, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label126), TRUE);

  entry_msidrech = gtk_entry_new ();
  gtk_widget_show (entry_msidrech);
  gtk_fixed_put (GTK_FIXED (fixed18), entry_msidrech, 248, 88);
  gtk_widget_set_size_request (entry_msidrech, 250, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_msidrech), 8226);

  scrolledwindow_rechcap = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow_rechcap);
  gtk_fixed_put (GTK_FIXED (fixed18), scrolledwindow_rechcap, 0, 200);
  gtk_widget_set_size_request (scrolledwindow_rechcap, 620, 220);

  viewport2 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow_rechcap), viewport2);

  fixed29 = gtk_fixed_new ();
  gtk_widget_show (fixed29);
  gtk_container_add (GTK_CONTAINER (viewport2), fixed29);

  treeview_mstxtrech = gtk_tree_view_new ();
  gtk_widget_show (treeview_mstxtrech);
  gtk_fixed_put (GTK_FIXED (fixed29), treeview_mstxtrech, 0, 0);
  gtk_widget_set_size_request (treeview_mstxtrech, 800, 600);

  button_mscnfrech = gtk_button_new ();
  gtk_widget_show (button_mscnfrech);
  gtk_fixed_put (GTK_FIXED (fixed18), button_mscnfrech, 512, 88);
  gtk_widget_set_size_request (button_mscnfrech, 105, 29);

  alignment74 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment74);
  gtk_container_add (GTK_CONTAINER (button_mscnfrech), alignment74);

  hbox74 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox74);
  gtk_container_add (GTK_CONTAINER (alignment74), hbox74);

  image100 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image100);
  gtk_box_pack_start (GTK_BOX (hbox74), image100, FALSE, FALSE, 0);

  label186 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>confirmer</b></span>"));
  gtk_widget_show (label186);
  gtk_box_pack_start (GTK_BOX (hbox74), label186, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label186), TRUE);

  label_msidrech = gtk_label_new (_("<span foreground=\"black\" ><b>Tapez l'identifiant a rechercher :</b></span>"));
  gtk_widget_show (label_msidrech);
  gtk_fixed_put (GTK_FIXED (fixed18), label_msidrech, 0, 80);
  gtk_widget_set_size_request (label_msidrech, 256, 40);
  gtk_label_set_use_markup (GTK_LABEL (label_msidrech), TRUE);

  label214 = gtk_label_new (_("<span foreground=\"black\" ><b>Choisir le critere a rechercher :</b></span>"));
  gtk_widget_show (label214);
  gtk_fixed_put (GTK_FIXED (fixed18), label214, 0, 24);
  gtk_widget_set_size_request (label214, 297, 49);
  gtk_label_set_use_markup (GTK_LABEL (label214), TRUE);

  combobox_mscrrech = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_mscrrech);
  gtk_fixed_put (GTK_FIXED (fixed18), combobox_mscrrech, 272, 40);
  gtk_widget_set_size_request (combobox_mscrrech, 163, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mscrrech), _("idcapteur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mscrrech), _("zone_ajout"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mscrrech), _("type"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mscrrech), _("marque"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mscrrech), _("etat_fct"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_mscrrech), _("annee_fct"));

  button_qrechcap = gtk_button_new ();
  gtk_widget_show (button_qrechcap);
  gtk_fixed_put (GTK_FIXED (fixed18), button_qrechcap, 535, 0);
  gtk_widget_set_size_request (button_qrechcap, 85, 29);

  alignment90 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment90);
  gtk_container_add (GTK_CONTAINER (button_qrechcap), alignment90);

  hbox90 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox90);
  gtk_container_add (GTK_CONTAINER (alignment90), hbox90);

  image117 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image117);
  gtk_box_pack_start (GTK_BOX (hbox90), image117, FALSE, FALSE, 0);

  label213 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>quitter</b></span>"));
  gtk_widget_show (label213);
  gtk_box_pack_start (GTK_BOX (hbox90), label213, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label213), TRUE);

  label_mstxtrech = gtk_label_new (_("<span foreground=\"blue\" ><b>Le champ a recherche est :</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed18), label_mstxtrech, 48, 136);
  gtk_widget_set_size_request (label_mstxtrech, 193, 41);
  gtk_label_set_use_markup (GTK_LABEL (label_mstxtrech), TRUE);

  label_msidaltrech = gtk_label_new (_("<span foreground=\"red\" ><b>Donn\303\251e invalide</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed18), label_msidaltrech, 288, 128);
  gtk_widget_set_size_request (label_msidaltrech, 169, 41);
  gtk_label_set_use_markup (GTK_LABEL (label_msidaltrech), TRUE);

  g_signal_connect ((gpointer) button_msretrech, "clicked",
                    G_CALLBACK (on_button_msretrech_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_mstxtrech, "row_activated",
                    G_CALLBACK (on_treeview_mstxtrech_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_mscnfrech, "clicked",
                    G_CALLBACK (on_button_mscnfrech_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_qrechcap, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (rechcap, rechcap, "rechcap");
  GLADE_HOOKUP_OBJECT (rechcap, fixed18, "fixed18");
  GLADE_HOOKUP_OBJECT (rechcap, image69, "image69");
  GLADE_HOOKUP_OBJECT (rechcap, button_msretrech, "button_msretrech");
  GLADE_HOOKUP_OBJECT (rechcap, alignment52, "alignment52");
  GLADE_HOOKUP_OBJECT (rechcap, hbox52, "hbox52");
  GLADE_HOOKUP_OBJECT (rechcap, image70, "image70");
  GLADE_HOOKUP_OBJECT (rechcap, label126, "label126");
  GLADE_HOOKUP_OBJECT (rechcap, entry_msidrech, "entry_msidrech");
  GLADE_HOOKUP_OBJECT (rechcap, scrolledwindow_rechcap, "scrolledwindow_rechcap");
  GLADE_HOOKUP_OBJECT (rechcap, viewport2, "viewport2");
  GLADE_HOOKUP_OBJECT (rechcap, fixed29, "fixed29");
  GLADE_HOOKUP_OBJECT (rechcap, treeview_mstxtrech, "treeview_mstxtrech");
  GLADE_HOOKUP_OBJECT (rechcap, button_mscnfrech, "button_mscnfrech");
  GLADE_HOOKUP_OBJECT (rechcap, alignment74, "alignment74");
  GLADE_HOOKUP_OBJECT (rechcap, hbox74, "hbox74");
  GLADE_HOOKUP_OBJECT (rechcap, image100, "image100");
  GLADE_HOOKUP_OBJECT (rechcap, label186, "label186");
  GLADE_HOOKUP_OBJECT (rechcap, label_msidrech, "label_msidrech");
  GLADE_HOOKUP_OBJECT (rechcap, label214, "label214");
  GLADE_HOOKUP_OBJECT (rechcap, combobox_mscrrech, "combobox_mscrrech");
  GLADE_HOOKUP_OBJECT (rechcap, button_qrechcap, "button_qrechcap");
  GLADE_HOOKUP_OBJECT (rechcap, alignment90, "alignment90");
  GLADE_HOOKUP_OBJECT (rechcap, hbox90, "hbox90");
  GLADE_HOOKUP_OBJECT (rechcap, image117, "image117");
  GLADE_HOOKUP_OBJECT (rechcap, label213, "label213");
  GLADE_HOOKUP_OBJECT (rechcap, label_mstxtrech, "label_mstxtrech");
  GLADE_HOOKUP_OBJECT (rechcap, label_msidaltrech, "label_msidaltrech");

  return rechcap;
}

GtkWidget*
create_suppcap (void)
{
  GtkWidget *suppcap;
  GtkWidget *fixed26;
  GtkWidget *entry_msidsp;
  GtkWidget *image118;
  GtkWidget *label_msidsp;
  GtkWidget *radiobutton_msnsp;
  GSList *radiobutton_msnsp_group = NULL;
  GtkWidget *radiobutton_msosp;
  GtkWidget *button_mscnfsp;
  GtkWidget *alignment75;
  GtkWidget *hbox75;
  GtkWidget *image101;
  GtkWidget *label188;
  GtkWidget *button_msanlsp;
  GtkWidget *alignment76;
  GtkWidget *hbox76;
  GtkWidget *image102;
  GtkWidget *label189;
  GtkWidget *button_qspcap;
  GtkWidget *alignment91;
  GtkWidget *hbox91;
  GtkWidget *image119;
  GtkWidget *label215;
  GtkWidget *label_msmsgsp;
  GtkWidget *label_msaltsp;

  suppcap = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (suppcap, 620, 430);
  gtk_window_set_title (GTK_WINDOW (suppcap), _("Suppression capteur"));

  fixed26 = gtk_fixed_new ();
  gtk_widget_show (fixed26);
  gtk_container_add (GTK_CONTAINER (suppcap), fixed26);

  entry_msidsp = gtk_entry_new ();
  gtk_widget_show (entry_msidsp);
  gtk_fixed_put (GTK_FIXED (fixed26), entry_msidsp, 168, 48);
  gtk_widget_set_size_request (entry_msidsp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_msidsp), 8226);

  image118 = create_pixmap (suppcap, "cp1.png");
  gtk_widget_show (image118);
  gtk_fixed_put (GTK_FIXED (fixed26), image118, 0, 0);
  gtk_widget_set_size_request (image118, 620, 430);

  label_msidsp = gtk_label_new (_("<span foreground=\"black\" ><b>Tapez l'identifiant a supprimer :</b></span>"));
  gtk_widget_show (label_msidsp);
  gtk_fixed_put (GTK_FIXED (fixed26), label_msidsp, 144, 0);
  gtk_widget_set_size_request (label_msidsp, 224, 41);
  gtk_label_set_use_markup (GTK_LABEL (label_msidsp), TRUE);

  radiobutton_msnsp = gtk_radio_button_new_with_mnemonic (NULL, _("Non"));
  gtk_widget_show (radiobutton_msnsp);
  gtk_fixed_put (GTK_FIXED (fixed26), radiobutton_msnsp, 136, 96);
  gtk_widget_set_size_request (radiobutton_msnsp, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_msnsp), radiobutton_msnsp_group);
  radiobutton_msnsp_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_msnsp));

  radiobutton_msosp = gtk_radio_button_new_with_mnemonic (NULL, _("Oui"));
  gtk_widget_show (radiobutton_msosp);
  gtk_fixed_put (GTK_FIXED (fixed26), radiobutton_msosp, 280, 96);
  gtk_widget_set_size_request (radiobutton_msosp, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_msosp), radiobutton_msnsp_group);
  radiobutton_msnsp_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_msosp));

  button_mscnfsp = gtk_button_new ();
  gtk_widget_show (button_mscnfsp);
  gtk_fixed_put (GTK_FIXED (fixed26), button_mscnfsp, 128, 344);
  gtk_widget_set_size_request (button_mscnfsp, 105, 29);

  alignment75 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment75);
  gtk_container_add (GTK_CONTAINER (button_mscnfsp), alignment75);

  hbox75 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox75);
  gtk_container_add (GTK_CONTAINER (alignment75), hbox75);

  image101 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image101);
  gtk_box_pack_start (GTK_BOX (hbox75), image101, FALSE, FALSE, 0);

  label188 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>confirmer</b></span>"));
  gtk_widget_show (label188);
  gtk_box_pack_start (GTK_BOX (hbox75), label188, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label188), TRUE);

  button_msanlsp = gtk_button_new ();
  gtk_widget_show (button_msanlsp);
  gtk_fixed_put (GTK_FIXED (fixed26), button_msanlsp, 280, 344);
  gtk_widget_set_size_request (button_msanlsp, 105, 29);

  alignment76 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment76);
  gtk_container_add (GTK_CONTAINER (button_msanlsp), alignment76);

  hbox76 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox76);
  gtk_container_add (GTK_CONTAINER (alignment76), hbox76);

  image102 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image102);
  gtk_box_pack_start (GTK_BOX (hbox76), image102, FALSE, FALSE, 0);

  label189 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>annuler</b></span>"));
  gtk_widget_show (label189);
  gtk_box_pack_start (GTK_BOX (hbox76), label189, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label189), TRUE);

  button_qspcap = gtk_button_new ();
  gtk_widget_show (button_qspcap);
  gtk_fixed_put (GTK_FIXED (fixed26), button_qspcap, 535, 0);
  gtk_widget_set_size_request (button_qspcap, 85, 29);

  alignment91 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment91);
  gtk_container_add (GTK_CONTAINER (button_qspcap), alignment91);

  hbox91 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox91);
  gtk_container_add (GTK_CONTAINER (alignment91), hbox91);

  image119 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image119);
  gtk_box_pack_start (GTK_BOX (hbox91), image119, FALSE, FALSE, 0);

  label215 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>quitter</b></span>"));
  gtk_widget_show (label215);
  gtk_box_pack_start (GTK_BOX (hbox91), label215, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label215), TRUE);

  label_msmsgsp = gtk_label_new (_("<span foreground=\"blue\" ><b>Vous etes sure de supprimer</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed26), label_msmsgsp, 120, 136);
  gtk_widget_set_size_request (label_msmsgsp, 256, 40);
  gtk_label_set_use_markup (GTK_LABEL (label_msmsgsp), TRUE);

  label_msaltsp = gtk_label_new (_("<span foreground=\"red\" ><b>Donn\303\251e invalide !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed26), label_msaltsp, 168, 288);
  gtk_widget_set_size_request (label_msaltsp, 176, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_msaltsp), TRUE);

  g_signal_connect ((gpointer) radiobutton_msnsp, "clicked",
                    G_CALLBACK (on_radiobutton_msnsp_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_msosp, "clicked",
                    G_CALLBACK (on_radiobutton_msosp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_mscnfsp, "clicked",
                    G_CALLBACK (on_button_mscnfsp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_msanlsp, "clicked",
                    G_CALLBACK (on_button_msanlsp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_qspcap, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (suppcap, suppcap, "suppcap");
  GLADE_HOOKUP_OBJECT (suppcap, fixed26, "fixed26");
  GLADE_HOOKUP_OBJECT (suppcap, entry_msidsp, "entry_msidsp");
  GLADE_HOOKUP_OBJECT (suppcap, image118, "image118");
  GLADE_HOOKUP_OBJECT (suppcap, label_msidsp, "label_msidsp");
  GLADE_HOOKUP_OBJECT (suppcap, radiobutton_msnsp, "radiobutton_msnsp");
  GLADE_HOOKUP_OBJECT (suppcap, radiobutton_msosp, "radiobutton_msosp");
  GLADE_HOOKUP_OBJECT (suppcap, button_mscnfsp, "button_mscnfsp");
  GLADE_HOOKUP_OBJECT (suppcap, alignment75, "alignment75");
  GLADE_HOOKUP_OBJECT (suppcap, hbox75, "hbox75");
  GLADE_HOOKUP_OBJECT (suppcap, image101, "image101");
  GLADE_HOOKUP_OBJECT (suppcap, label188, "label188");
  GLADE_HOOKUP_OBJECT (suppcap, button_msanlsp, "button_msanlsp");
  GLADE_HOOKUP_OBJECT (suppcap, alignment76, "alignment76");
  GLADE_HOOKUP_OBJECT (suppcap, hbox76, "hbox76");
  GLADE_HOOKUP_OBJECT (suppcap, image102, "image102");
  GLADE_HOOKUP_OBJECT (suppcap, label189, "label189");
  GLADE_HOOKUP_OBJECT (suppcap, button_qspcap, "button_qspcap");
  GLADE_HOOKUP_OBJECT (suppcap, alignment91, "alignment91");
  GLADE_HOOKUP_OBJECT (suppcap, hbox91, "hbox91");
  GLADE_HOOKUP_OBJECT (suppcap, image119, "image119");
  GLADE_HOOKUP_OBJECT (suppcap, label215, "label215");
  GLADE_HOOKUP_OBJECT (suppcap, label_msmsgsp, "label_msmsgsp");
  GLADE_HOOKUP_OBJECT (suppcap, label_msaltsp, "label_msaltsp");

  return suppcap;
}

GtkWidget*
create_fctcap (void)
{
  GtkWidget *fctcap;
  GtkWidget *fixed27;
  GtkObject *spinbutton_msjdfct_adj;
  GtkWidget *spinbutton_msjdfct;
  GtkObject *spinbutton_msmdfct_adj;
  GtkWidget *spinbutton_msmdfct;
  GtkObject *spinbutton_msadfct_adj;
  GtkWidget *spinbutton_msadfct;
  GtkWidget *image103;
  GtkWidget *button_msretfct;
  GtkWidget *alignment80;
  GtkWidget *hbox80;
  GtkWidget *image107;
  GtkWidget *label198;
  GtkWidget *button_mscnffct;
  GtkWidget *alignment78;
  GtkWidget *hbox78;
  GtkWidget *image105;
  GtkWidget *label196;
  GtkWidget *button_msmdffct;
  GtkWidget *alignment79;
  GtkWidget *hbox79;
  GtkWidget *image106;
  GtkWidget *label197;
  GtkWidget *button_msspfcap;
  GtkWidget *alignment82;
  GtkWidget *hbox82;
  GtkWidget *image109;
  GtkWidget *label200;
  GtkWidget *button_qfctcap;
  GtkWidget *alignment92;
  GtkWidget *hbox92;
  GtkWidget *image120;
  GtkWidget *label216;
  GtkWidget *button_msafffct;
  GtkWidget *alignment77;
  GtkWidget *hbox77;
  GtkWidget *image104;
  GtkWidget *label195;
  GtkWidget *radiobutton_mstfct;
  GSList *radiobutton_mstfct_group = NULL;
  GtkWidget *radiobutton_mshfct;
  GtkWidget *label_msdafffct;
  GtkWidget *label_mstpfct;
  GtkWidget *label_msidfct;
  GtkWidget *label_msdtfct;
  GtkWidget *label_msvlfct;
  GtkWidget *button_mschidfct;
  GtkWidget *alignment86;
  GtkWidget *hbox86;
  GtkWidget *image113;
  GtkWidget *label209;
  GtkWidget *scrolledwindow_fctcap;
  GtkWidget *viewport3;
  GtkWidget *fixed30;
  GtkWidget *treeview_mscapfct;
  GtkWidget *label_msajfct;
  GtkWidget *label_msmdffct;
  GtkWidget *label_msspfct;
  GtkObject *spinbutton_msmafffct_adj;
  GtkWidget *spinbutton_msmafffct;
  GtkObject *spinbutton_msaafffct_adj;
  GtkWidget *spinbutton_msaafffct;
  GtkWidget *combobox_idfct;
  GtkObject *spinbutton_msvalfct_adj;
  GtkWidget *spinbutton_msvalfct;
  GtkWidget *label_msvrdt;
  GtkWidget *label_mssvalfct;

  fctcap = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (fctcap, 620, 430);
  gtk_window_set_title (GTK_WINDOW (fctcap), _("Fonctionnement capteur"));

  fixed27 = gtk_fixed_new ();
  gtk_widget_show (fixed27);
  gtk_container_add (GTK_CONTAINER (fctcap), fixed27);

  spinbutton_msjdfct_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_msjdfct = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_msjdfct_adj), 1, 0);
  gtk_widget_show (spinbutton_msjdfct);
  gtk_fixed_put (GTK_FIXED (fixed27), spinbutton_msjdfct, 160, 72);
  gtk_widget_set_size_request (spinbutton_msjdfct, 60, 27);

  spinbutton_msmdfct_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_msmdfct = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_msmdfct_adj), 1, 0);
  gtk_widget_show (spinbutton_msmdfct);
  gtk_fixed_put (GTK_FIXED (fixed27), spinbutton_msmdfct, 232, 72);
  gtk_widget_set_size_request (spinbutton_msmdfct, 60, 27);

  spinbutton_msadfct_adj = gtk_adjustment_new (2020, 1900, 2100, 1, 10, 10);
  spinbutton_msadfct = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_msadfct_adj), 1, 0);
  gtk_widget_show (spinbutton_msadfct);
  gtk_fixed_put (GTK_FIXED (fixed27), spinbutton_msadfct, 312, 72);
  gtk_widget_set_size_request (spinbutton_msadfct, 60, 27);

  image103 = create_pixmap (fctcap, "cp1.png");
  gtk_widget_show (image103);
  gtk_fixed_put (GTK_FIXED (fixed27), image103, 0, 0);
  gtk_widget_set_size_request (image103, 620, 430);

  button_msretfct = gtk_button_new ();
  gtk_widget_show (button_msretfct);
  gtk_fixed_put (GTK_FIXED (fixed27), button_msretfct, 445, 0);
  gtk_widget_set_size_request (button_msretfct, 85, 29);

  alignment80 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment80);
  gtk_container_add (GTK_CONTAINER (button_msretfct), alignment80);

  hbox80 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox80);
  gtk_container_add (GTK_CONTAINER (alignment80), hbox80);

  image107 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image107);
  gtk_box_pack_start (GTK_BOX (hbox80), image107, FALSE, FALSE, 0);

  label198 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>retour</b></span>\n"));
  gtk_widget_show (label198);
  gtk_box_pack_start (GTK_BOX (hbox80), label198, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label198), TRUE);

  button_mscnffct = gtk_button_new ();
  gtk_widget_show (button_mscnffct);
  gtk_fixed_put (GTK_FIXED (fixed27), button_mscnffct, 208, 200);
  gtk_widget_set_size_request (button_mscnffct, 105, 29);

  alignment78 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment78);
  gtk_container_add (GTK_CONTAINER (button_mscnffct), alignment78);

  hbox78 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox78);
  gtk_container_add (GTK_CONTAINER (alignment78), hbox78);

  image105 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image105);
  gtk_box_pack_start (GTK_BOX (hbox78), image105, FALSE, FALSE, 0);

  label196 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>ajouter</b></span>"));
  gtk_widget_show (label196);
  gtk_box_pack_start (GTK_BOX (hbox78), label196, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label196), TRUE);

  button_msmdffct = gtk_button_new ();
  gtk_widget_show (button_msmdffct);
  gtk_fixed_put (GTK_FIXED (fixed27), button_msmdffct, 352, 200);
  gtk_widget_set_size_request (button_msmdffct, 105, 29);

  alignment79 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment79);
  gtk_container_add (GTK_CONTAINER (button_msmdffct), alignment79);

  hbox79 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox79);
  gtk_container_add (GTK_CONTAINER (alignment79), hbox79);

  image106 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image106);
  gtk_box_pack_start (GTK_BOX (hbox79), image106, FALSE, FALSE, 0);

  label197 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>modifier</b></span>"));
  gtk_widget_show (label197);
  gtk_box_pack_start (GTK_BOX (hbox79), label197, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label197), TRUE);

  button_msspfcap = gtk_button_new ();
  gtk_widget_show (button_msspfcap);
  gtk_fixed_put (GTK_FIXED (fixed27), button_msspfcap, 496, 200);
  gtk_widget_set_size_request (button_msspfcap, 105, 29);

  alignment82 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment82);
  gtk_container_add (GTK_CONTAINER (button_msspfcap), alignment82);

  hbox82 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox82);
  gtk_container_add (GTK_CONTAINER (alignment82), hbox82);

  image109 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image109);
  gtk_box_pack_start (GTK_BOX (hbox82), image109, FALSE, FALSE, 0);

  label200 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>supprimer</b></span>"));
  gtk_widget_show (label200);
  gtk_box_pack_start (GTK_BOX (hbox82), label200, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label200), TRUE);

  button_qfctcap = gtk_button_new ();
  gtk_widget_show (button_qfctcap);
  gtk_fixed_put (GTK_FIXED (fixed27), button_qfctcap, 535, 0);
  gtk_widget_set_size_request (button_qfctcap, 85, 29);

  alignment92 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment92);
  gtk_container_add (GTK_CONTAINER (button_qfctcap), alignment92);

  hbox92 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox92);
  gtk_container_add (GTK_CONTAINER (alignment92), hbox92);

  image120 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image120);
  gtk_box_pack_start (GTK_BOX (hbox92), image120, FALSE, FALSE, 0);

  label216 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>quitter</b></span>"));
  gtk_widget_show (label216);
  gtk_box_pack_start (GTK_BOX (hbox92), label216, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label216), TRUE);

  button_msafffct = gtk_button_new ();
  gtk_widget_show (button_msafffct);
  gtk_fixed_put (GTK_FIXED (fixed27), button_msafffct, 72, 200);
  gtk_widget_set_size_request (button_msafffct, 105, 29);

  alignment77 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment77);
  gtk_container_add (GTK_CONTAINER (button_msafffct), alignment77);

  hbox77 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox77);
  gtk_container_add (GTK_CONTAINER (alignment77), hbox77);

  image104 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image104);
  gtk_box_pack_start (GTK_BOX (hbox77), image104, FALSE, FALSE, 0);

  label195 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>afficher</b></span>"));
  gtk_widget_show (label195);
  gtk_box_pack_start (GTK_BOX (hbox77), label195, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label195), TRUE);

  radiobutton_mstfct = gtk_radio_button_new_with_mnemonic (NULL, _("temperature"));
  gtk_widget_show (radiobutton_mstfct);
  gtk_fixed_put (GTK_FIXED (fixed27), radiobutton_mstfct, 152, 8);
  gtk_widget_set_size_request (radiobutton_mstfct, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_mstfct), radiobutton_mstfct_group);
  radiobutton_mstfct_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_mstfct));

  radiobutton_mshfct = gtk_radio_button_new_with_mnemonic (NULL, _("humidite"));
  gtk_widget_show (radiobutton_mshfct);
  gtk_fixed_put (GTK_FIXED (fixed27), radiobutton_mshfct, 288, 8);
  gtk_widget_set_size_request (radiobutton_mshfct, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_mshfct), radiobutton_mstfct_group);
  radiobutton_mstfct_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_mshfct));

  label_msdafffct = gtk_label_new (_("<span foreground=\"blue\" ><b>Tapez la date a afficher :</b></span>"));
  gtk_widget_show (label_msdafffct);
  gtk_fixed_put (GTK_FIXED (fixed27), label_msdafffct, 0, 240);
  gtk_widget_set_size_request (label_msdafffct, 233, 25);
  gtk_label_set_use_markup (GTK_LABEL (label_msdafffct), TRUE);

  label_mstpfct = gtk_label_new (_("<span foreground=\"black\" ><b>Type :</b></span>"));
  gtk_widget_show (label_mstpfct);
  gtk_fixed_put (GTK_FIXED (fixed27), label_mstpfct, 40, 0);
  gtk_widget_set_size_request (label_mstpfct, 89, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_mstpfct), TRUE);

  label_msidfct = gtk_label_new (_("<span foreground=\"black\" ><b>Identifiant :</b></span>"));
  gtk_widget_show (label_msidfct);
  gtk_fixed_put (GTK_FIXED (fixed27), label_msidfct, 16, 32);
  gtk_widget_set_size_request (label_msidfct, 97, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_msidfct), TRUE);

  label_msdtfct = gtk_label_new (_("<span foreground=\"black\" ><b>Date :</b></span>"));
  gtk_widget_show (label_msdtfct);
  gtk_fixed_put (GTK_FIXED (fixed27), label_msdtfct, 48, 64);
  gtk_widget_set_size_request (label_msdtfct, 73, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_msdtfct), TRUE);

  label_msvlfct = gtk_label_new (_("<span foreground=\"black\" ><b>Valeur :</b></span>"));
  gtk_widget_show (label_msvlfct);
  gtk_fixed_put (GTK_FIXED (fixed27), label_msvlfct, 40, 96);
  gtk_widget_set_size_request (label_msvlfct, 73, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_msvlfct), TRUE);

  button_mschidfct = gtk_button_new ();
  gtk_widget_show (button_mschidfct);
  gtk_fixed_put (GTK_FIXED (fixed27), button_mschidfct, 344, 32);
  gtk_widget_set_size_request (button_mschidfct, 85, 29);

  alignment86 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment86);
  gtk_container_add (GTK_CONTAINER (button_mschidfct), alignment86);

  hbox86 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox86);
  gtk_container_add (GTK_CONTAINER (alignment86), hbox86);

  image113 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image113);
  gtk_box_pack_start (GTK_BOX (hbox86), image113, FALSE, FALSE, 0);

  label209 = gtk_label_new_with_mnemonic (_("<span foreground=\"black\" ><b>charger</b></span>"));
  gtk_widget_show (label209);
  gtk_box_pack_start (GTK_BOX (hbox86), label209, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label209), TRUE);

  scrolledwindow_fctcap = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow_fctcap);
  gtk_fixed_put (GTK_FIXED (fixed27), scrolledwindow_fctcap, 48, 278);
  gtk_widget_set_size_request (scrolledwindow_fctcap, 544, 152);

  viewport3 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow_fctcap), viewport3);

  fixed30 = gtk_fixed_new ();
  gtk_widget_show (fixed30);
  gtk_container_add (GTK_CONTAINER (viewport3), fixed30);

  treeview_mscapfct = gtk_tree_view_new ();
  gtk_widget_show (treeview_mscapfct);
  gtk_fixed_put (GTK_FIXED (fixed30), treeview_mscapfct, 0, 0);
  gtk_widget_set_size_request (treeview_mscapfct, 530, 10000);

  label_msajfct = gtk_label_new (_("<span foreground=\"green\" ><b>Ajout avec succes</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed27), label_msajfct, 224, 128);
  gtk_widget_set_size_request (label_msajfct, 153, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_msajfct), TRUE);

  label_msmdffct = gtk_label_new (_("<span foreground=\"green\" ><b>Modification avec succes</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed27), label_msmdffct, 208, 128);
  gtk_widget_set_size_request (label_msmdffct, 193, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_msmdffct), TRUE);

  label_msspfct = gtk_label_new (_("<span foreground=\"green\" ><b>Suppression avec succes</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed27), label_msspfct, 208, 128);
  gtk_widget_set_size_request (label_msspfct, 193, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_msspfct), TRUE);

  spinbutton_msmafffct_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_msmafffct = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_msmafffct_adj), 1, 0);
  gtk_widget_show (spinbutton_msmafffct);
  gtk_fixed_put (GTK_FIXED (fixed27), spinbutton_msmafffct, 232, 240);
  gtk_widget_set_size_request (spinbutton_msmafffct, 60, 27);

  spinbutton_msaafffct_adj = gtk_adjustment_new (2020, 1900, 2100, 1, 10, 10);
  spinbutton_msaafffct = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_msaafffct_adj), 1, 0);
  gtk_widget_show (spinbutton_msaafffct);
  gtk_fixed_put (GTK_FIXED (fixed27), spinbutton_msaafffct, 312, 240);
  gtk_widget_set_size_request (spinbutton_msaafffct, 60, 27);

  combobox_idfct = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_idfct);
  gtk_fixed_put (GTK_FIXED (fixed27), combobox_idfct, 160, 32);
  gtk_widget_set_size_request (combobox_idfct, 163, 29);

  spinbutton_msvalfct_adj = gtk_adjustment_new (0, -30, 300, 1, 10, 10);
  spinbutton_msvalfct = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_msvalfct_adj), 1, 2);
  gtk_widget_show (spinbutton_msvalfct);
  gtk_fixed_put (GTK_FIXED (fixed27), spinbutton_msvalfct, 160, 104);
  gtk_widget_set_size_request (spinbutton_msvalfct, 100, 27);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton_msvalfct), TRUE);

  label_msvrdt = gtk_label_new (_("<span foreground=\"red\" ><b>date deja remplie !</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed27), label_msvrdt, 208, 128);
  gtk_widget_set_size_request (label_msvrdt, 201, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_msvrdt), TRUE);

  label_mssvalfct = gtk_label_new (_("<span foreground=\"blue\" ><b>*champ obligatoire</b></span>"));
  gtk_fixed_put (GTK_FIXED (fixed27), label_mssvalfct, 320, 104);
  gtk_widget_set_size_request (label_mssvalfct, 161, 33);
  gtk_label_set_use_markup (GTK_LABEL (label_mssvalfct), TRUE);

  g_signal_connect ((gpointer) button_msretfct, "clicked",
                    G_CALLBACK (on_button_msretfct_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_mscnffct, "clicked",
                    G_CALLBACK (on_button_mscnffct_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_msmdffct, "clicked",
                    G_CALLBACK (on_button_msmdffct_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_msspfcap, "clicked",
                    G_CALLBACK (on_button_msspfcap_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_qfctcap, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) button_msafffct, "clicked",
                    G_CALLBACK (on_button_msafffct_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_mstfct, "toggled",
                    G_CALLBACK (on_radiobutton_mstfct_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_mshfct, "toggled",
                    G_CALLBACK (on_radiobutton_mshfct_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_mschidfct, "clicked",
                    G_CALLBACK (on_button_mschidfct_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_mscapfct, "row_activated",
                    G_CALLBACK (on_treeview_mscapfct_row_activated),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fctcap, fctcap, "fctcap");
  GLADE_HOOKUP_OBJECT (fctcap, fixed27, "fixed27");
  GLADE_HOOKUP_OBJECT (fctcap, spinbutton_msjdfct, "spinbutton_msjdfct");
  GLADE_HOOKUP_OBJECT (fctcap, spinbutton_msmdfct, "spinbutton_msmdfct");
  GLADE_HOOKUP_OBJECT (fctcap, spinbutton_msadfct, "spinbutton_msadfct");
  GLADE_HOOKUP_OBJECT (fctcap, image103, "image103");
  GLADE_HOOKUP_OBJECT (fctcap, button_msretfct, "button_msretfct");
  GLADE_HOOKUP_OBJECT (fctcap, alignment80, "alignment80");
  GLADE_HOOKUP_OBJECT (fctcap, hbox80, "hbox80");
  GLADE_HOOKUP_OBJECT (fctcap, image107, "image107");
  GLADE_HOOKUP_OBJECT (fctcap, label198, "label198");
  GLADE_HOOKUP_OBJECT (fctcap, button_mscnffct, "button_mscnffct");
  GLADE_HOOKUP_OBJECT (fctcap, alignment78, "alignment78");
  GLADE_HOOKUP_OBJECT (fctcap, hbox78, "hbox78");
  GLADE_HOOKUP_OBJECT (fctcap, image105, "image105");
  GLADE_HOOKUP_OBJECT (fctcap, label196, "label196");
  GLADE_HOOKUP_OBJECT (fctcap, button_msmdffct, "button_msmdffct");
  GLADE_HOOKUP_OBJECT (fctcap, alignment79, "alignment79");
  GLADE_HOOKUP_OBJECT (fctcap, hbox79, "hbox79");
  GLADE_HOOKUP_OBJECT (fctcap, image106, "image106");
  GLADE_HOOKUP_OBJECT (fctcap, label197, "label197");
  GLADE_HOOKUP_OBJECT (fctcap, button_msspfcap, "button_msspfcap");
  GLADE_HOOKUP_OBJECT (fctcap, alignment82, "alignment82");
  GLADE_HOOKUP_OBJECT (fctcap, hbox82, "hbox82");
  GLADE_HOOKUP_OBJECT (fctcap, image109, "image109");
  GLADE_HOOKUP_OBJECT (fctcap, label200, "label200");
  GLADE_HOOKUP_OBJECT (fctcap, button_qfctcap, "button_qfctcap");
  GLADE_HOOKUP_OBJECT (fctcap, alignment92, "alignment92");
  GLADE_HOOKUP_OBJECT (fctcap, hbox92, "hbox92");
  GLADE_HOOKUP_OBJECT (fctcap, image120, "image120");
  GLADE_HOOKUP_OBJECT (fctcap, label216, "label216");
  GLADE_HOOKUP_OBJECT (fctcap, button_msafffct, "button_msafffct");
  GLADE_HOOKUP_OBJECT (fctcap, alignment77, "alignment77");
  GLADE_HOOKUP_OBJECT (fctcap, hbox77, "hbox77");
  GLADE_HOOKUP_OBJECT (fctcap, image104, "image104");
  GLADE_HOOKUP_OBJECT (fctcap, label195, "label195");
  GLADE_HOOKUP_OBJECT (fctcap, radiobutton_mstfct, "radiobutton_mstfct");
  GLADE_HOOKUP_OBJECT (fctcap, radiobutton_mshfct, "radiobutton_mshfct");
  GLADE_HOOKUP_OBJECT (fctcap, label_msdafffct, "label_msdafffct");
  GLADE_HOOKUP_OBJECT (fctcap, label_mstpfct, "label_mstpfct");
  GLADE_HOOKUP_OBJECT (fctcap, label_msidfct, "label_msidfct");
  GLADE_HOOKUP_OBJECT (fctcap, label_msdtfct, "label_msdtfct");
  GLADE_HOOKUP_OBJECT (fctcap, label_msvlfct, "label_msvlfct");
  GLADE_HOOKUP_OBJECT (fctcap, button_mschidfct, "button_mschidfct");
  GLADE_HOOKUP_OBJECT (fctcap, alignment86, "alignment86");
  GLADE_HOOKUP_OBJECT (fctcap, hbox86, "hbox86");
  GLADE_HOOKUP_OBJECT (fctcap, image113, "image113");
  GLADE_HOOKUP_OBJECT (fctcap, label209, "label209");
  GLADE_HOOKUP_OBJECT (fctcap, scrolledwindow_fctcap, "scrolledwindow_fctcap");
  GLADE_HOOKUP_OBJECT (fctcap, viewport3, "viewport3");
  GLADE_HOOKUP_OBJECT (fctcap, fixed30, "fixed30");
  GLADE_HOOKUP_OBJECT (fctcap, treeview_mscapfct, "treeview_mscapfct");
  GLADE_HOOKUP_OBJECT (fctcap, label_msajfct, "label_msajfct");
  GLADE_HOOKUP_OBJECT (fctcap, label_msmdffct, "label_msmdffct");
  GLADE_HOOKUP_OBJECT (fctcap, label_msspfct, "label_msspfct");
  GLADE_HOOKUP_OBJECT (fctcap, spinbutton_msmafffct, "spinbutton_msmafffct");
  GLADE_HOOKUP_OBJECT (fctcap, spinbutton_msaafffct, "spinbutton_msaafffct");
  GLADE_HOOKUP_OBJECT (fctcap, combobox_idfct, "combobox_idfct");
  GLADE_HOOKUP_OBJECT (fctcap, spinbutton_msvalfct, "spinbutton_msvalfct");
  GLADE_HOOKUP_OBJECT (fctcap, label_msvrdt, "label_msvrdt");
  GLADE_HOOKUP_OBJECT (fctcap, label_mssvalfct, "label_mssvalfct");

  return fctcap;
}

GtkWidget*
create_scajcap (void)
{
  GtkWidget *scajcap;
  GtkWidget *fixed31;
  GtkWidget *image121;
  GtkWidget *button_ok;
  GtkWidget *alignment93;
  GtkWidget *hbox93;
  GtkWidget *image122;
  GtkWidget *label217;

  scajcap = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (scajcap, 280, 150);
  gtk_window_set_title (GTK_WINDOW (scajcap), _("Ajout avec succes"));

  fixed31 = gtk_fixed_new ();
  gtk_widget_show (fixed31);
  gtk_container_add (GTK_CONTAINER (scajcap), fixed31);

  image121 = create_pixmap (scajcap, "bacgrouna.png");
  gtk_widget_show (image121);
  gtk_fixed_put (GTK_FIXED (fixed31), image121, 0, 0);
  gtk_widget_set_size_request (image121, 280, 150);

  button_ok = gtk_button_new ();
  gtk_widget_show (button_ok);
  gtk_fixed_put (GTK_FIXED (fixed31), button_ok, 104, 120);
  gtk_widget_set_size_request (button_ok, 60, 29);

  alignment93 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment93);
  gtk_container_add (GTK_CONTAINER (button_ok), alignment93);

  hbox93 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox93);
  gtk_container_add (GTK_CONTAINER (alignment93), hbox93);

  image122 = gtk_image_new_from_stock ("gtk-yes", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image122);
  gtk_box_pack_start (GTK_BOX (hbox93), image122, FALSE, FALSE, 0);

  label217 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_show (label217);
  gtk_box_pack_start (GTK_BOX (hbox93), label217, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_ok, "clicked",
                    G_CALLBACK (on_button_ok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (scajcap, scajcap, "scajcap");
  GLADE_HOOKUP_OBJECT (scajcap, fixed31, "fixed31");
  GLADE_HOOKUP_OBJECT (scajcap, image121, "image121");
  GLADE_HOOKUP_OBJECT (scajcap, button_ok, "button_ok");
  GLADE_HOOKUP_OBJECT (scajcap, alignment93, "alignment93");
  GLADE_HOOKUP_OBJECT (scajcap, hbox93, "hbox93");
  GLADE_HOOKUP_OBJECT (scajcap, image122, "image122");
  GLADE_HOOKUP_OBJECT (scajcap, label217, "label217");

  return scajcap;
}

GtkWidget*
create_scmdfcap (void)
{
  GtkWidget *scmdfcap;
  GtkWidget *fixed32;
  GtkWidget *image123;
  GtkWidget *button_okmdfcap;
  GtkWidget *alignment94;
  GtkWidget *hbox94;
  GtkWidget *image124;
  GtkWidget *label218;

  scmdfcap = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (scmdfcap, 280, 150);
  gtk_window_set_title (GTK_WINDOW (scmdfcap), _("modification avec succes"));

  fixed32 = gtk_fixed_new ();
  gtk_widget_show (fixed32);
  gtk_container_add (GTK_CONTAINER (scmdfcap), fixed32);

  image123 = create_pixmap (scmdfcap, "bacgrounm.png");
  gtk_widget_show (image123);
  gtk_fixed_put (GTK_FIXED (fixed32), image123, 0, 0);
  gtk_widget_set_size_request (image123, 280, 150);

  button_okmdfcap = gtk_button_new ();
  gtk_widget_show (button_okmdfcap);
  gtk_fixed_put (GTK_FIXED (fixed32), button_okmdfcap, 120, 120);
  gtk_widget_set_size_request (button_okmdfcap, 60, 29);

  alignment94 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment94);
  gtk_container_add (GTK_CONTAINER (button_okmdfcap), alignment94);

  hbox94 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox94);
  gtk_container_add (GTK_CONTAINER (alignment94), hbox94);

  image124 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image124);
  gtk_box_pack_start (GTK_BOX (hbox94), image124, FALSE, FALSE, 0);

  label218 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_show (label218);
  gtk_box_pack_start (GTK_BOX (hbox94), label218, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_okmdfcap, "clicked",
                    G_CALLBACK (on_button_okmdfcap_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (scmdfcap, scmdfcap, "scmdfcap");
  GLADE_HOOKUP_OBJECT (scmdfcap, fixed32, "fixed32");
  GLADE_HOOKUP_OBJECT (scmdfcap, image123, "image123");
  GLADE_HOOKUP_OBJECT (scmdfcap, button_okmdfcap, "button_okmdfcap");
  GLADE_HOOKUP_OBJECT (scmdfcap, alignment94, "alignment94");
  GLADE_HOOKUP_OBJECT (scmdfcap, hbox94, "hbox94");
  GLADE_HOOKUP_OBJECT (scmdfcap, image124, "image124");
  GLADE_HOOKUP_OBJECT (scmdfcap, label218, "label218");

  return scmdfcap;
}

GtkWidget*
create_spcap (void)
{
  GtkWidget *spcap;
  GtkWidget *fixed33;
  GtkWidget *image125;
  GtkWidget *button_okspcap;
  GtkWidget *alignment95;
  GtkWidget *hbox95;
  GtkWidget *image126;
  GtkWidget *label219;

  spcap = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (spcap, 280, 150);
  gtk_window_set_title (GTK_WINDOW (spcap), _("suppression avec succes"));

  fixed33 = gtk_fixed_new ();
  gtk_widget_show (fixed33);
  gtk_container_add (GTK_CONTAINER (spcap), fixed33);

  image125 = create_pixmap (spcap, "bacgrouns.png");
  gtk_widget_show (image125);
  gtk_fixed_put (GTK_FIXED (fixed33), image125, 0, 0);
  gtk_widget_set_size_request (image125, 280, 150);

  button_okspcap = gtk_button_new ();
  gtk_widget_show (button_okspcap);
  gtk_fixed_put (GTK_FIXED (fixed33), button_okspcap, 104, 120);
  gtk_widget_set_size_request (button_okspcap, 60, 29);

  alignment95 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment95);
  gtk_container_add (GTK_CONTAINER (button_okspcap), alignment95);

  hbox95 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox95);
  gtk_container_add (GTK_CONTAINER (alignment95), hbox95);

  image126 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image126);
  gtk_box_pack_start (GTK_BOX (hbox95), image126, FALSE, FALSE, 0);

  label219 = gtk_label_new_with_mnemonic (_("OK"));
  gtk_widget_show (label219);
  gtk_box_pack_start (GTK_BOX (hbox95), label219, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_okspcap, "clicked",
                    G_CALLBACK (on_button_okspcap_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (spcap, spcap, "spcap");
  GLADE_HOOKUP_OBJECT (spcap, fixed33, "fixed33");
  GLADE_HOOKUP_OBJECT (spcap, image125, "image125");
  GLADE_HOOKUP_OBJECT (spcap, button_okspcap, "button_okspcap");
  GLADE_HOOKUP_OBJECT (spcap, alignment95, "alignment95");
  GLADE_HOOKUP_OBJECT (spcap, hbox95, "hbox95");
  GLADE_HOOKUP_OBJECT (spcap, image126, "image126");
  GLADE_HOOKUP_OBJECT (spcap, label219, "label219");

  return spcap;
}

