/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gcap (void);
GtkWidget* create_ajcap (void);
GtkWidget* create_mdfcap (void);
GtkWidget* create_rechcap (void);
GtkWidget* create_suppcap (void);
GtkWidget* create_fctcap (void);
GtkWidget* create_scajcap (void);
GtkWidget* create_scmdfcap (void);
GtkWidget* create_spcap (void);
